# Generated by Django 3.0.7 on 2020-10-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('site', models.URLField()),
                ('code', models.URLField()),
                ('cover', models.ImageField(upload_to='project_imgs')),
                ('mockup', models.ImageField(upload_to='project_imgs')),
                ('role', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('overview', models.CharField(max_length=400)),
            ],
        ),
    ]
